feat: add api and directivfes Chinese docs
enpitsuLin/tres pull request #1
Opened 2024-02-11 13:44 UTC by X-smart

2024-02-11 15:12 UTC, enpitsuLin requested changes

2024-02-11 15:12 UTC, enpitsuLin commented on docs/zh/api/events.md
> +默认情况下，不会组织事件冒泡。可以通过使用`blocks-pointer-events` 属性来实现此行为。
`组织` to `阻止`

2024-02-11 15:12 UTC, enpitsuLin commented on docs/zh/api/instances-arguments-and-props.md
> +## 属性
我会倾向于不翻译`Props/Prop`这个固有词汇，像 Vuejs 文档一样，在概念上也不是简单的 property 的缩写之类的

2024-02-12 00:24 UTC, X-smart commented
已做更正

2024-02-12 02:11 UTC, enpitsuLin approved these changes

2024-02-12 02:11 UTC, enpitsuLin commented on docs/zh/api/composables.md
> +`useRenderLoop` 是 **TresJS** 动画的核心。它可以注册一个回调函数，该函数将在本地刷新时被调用。这是 **TresJS** 中最重要的可组合项。
> It allows you to register a callback that will be called on native refresh rate.

感觉应该

> 它可以注册一个回调函数，该函数将在原生刷新率下被调用

***

可组合项 `composable` 应该按 Vue 官方翻译成 `组合式函数`, 其余的类似的地方也应该注意下

2024-02-12 02:12 UTC, enpitsuLin commented
先合入了然后下午我把我的部分完成一下，再简单校对下，昨天下午临时有约没什么进展😇

2024-02-12 02:12 UTC, merged